### ISSUE TITLE
contributor covenant badge

### ISSUE THREAD

**Issue by sethvincent** [EthicalSource/contributor_covenant#339]
I've started using a badge placed in github readme files next to travis ci, project version, & other badges to indicate the project has a code of conduct.

I've been using markdown similar to the following:

``` md
[![conduct][https://img.shields.io/badge/code%20of%20conduct-contributor%20covenant-green.svg?style=flat-square]][http://contributor-covenant.org/version/1/4/]
```

Usually I'll link to the specific code of conduct file in a project repository rather than link to the site.

Here's what the badge looks like:

[![conduct](https://img.shields.io/badge/code%20of%20conduct-contributor%20covenant-green.svg?style=flat-square)](http://contributor-covenant.org/version/1/4/)

I like the idea of raising the visibility of the code of conduct through the badge and wanted to bring it up here in case others are interested.

It could be neat to have an official badge! Might look different than the one I've been using so far.

**Comment by CoralineAda** [comment]
I love this idea! We’re currently working on ways to make community-related files (like a CoC or contributing doc) more visible and I’m going to share this with our UX person. Thanks!

What’s your Twitter handle? I’d love to tweet this tip with attribution.

Best,
Coraline

**Comment by sethvincent** [comment]
@CoralineAda Awesome! The improvements to community docs visibility sounds exciting. I'm looking forward to that.

Here's my twitter: https://twitter.com/sethdvincent

**Comment by adamretter** [comment]
Oooh... I would like a nice badge for our projects too!

**Comment by JoshuaKGoldberg** [comment]
Bumping this old thread because I found it googling for almost the exact title 😄 - would you accept a PR that adds a badge to the README.md of this repo?

Markdown version:
[![Code of Conduct: Contributor Covenant](https://img.shields.io/badge/code_of_conduct-contributor_covenant-14cc21)](https://github.com/EthicalSource/contributor_covenant)


```md
[![Code of Conduct: Contributor Covenant](https://img.shields.io/badge/code_of_conduct-contributor_covenant-14cc21)](https://github.com/EthicalSource/contributor_covenant)
```

HTML version: <a href="https://github.com/EthicalSource/contributor_covenant">
  <img alt="Code of Conduct: Contributor Covenant" src="https://img.shields.io/badge/code_of_conduct-contributor_covenant-14cc21" />
</a>


```html
<a href="https://github.com/EthicalSource/contributor_covenant">
  <img alt="Code of Conduct: Contributor Covenant" src="https://img.shields.io/badge/code_of_conduct-contributor_covenant-14cc21" />
</a>
```

**Comment by CoralineAda** [comment]
@JoshuaKGoldberg Yes please! Feel free to open a PR, and let me know if you need any help.

**Comment by Azizkhan1122** [comment]
Ugff
