### ISSUE TITLE
[query] Preferred copyright line

### ISSUE THREAD

**Issue by lofidevops** [EthicalSource/contributor_covenant#473]
I'd like to notate the copyright of the covenant file. There isn't a fixed form for copyright notation, but it typically looks something like:

````
Package name
https://example.org/optional/url
Copyright 1984-2017 Alice P. Hacker and contributors
* any obligatory text block from license here *
* and/or SPDX stuff if you like that kind of thing *
````

Is there a preferred form for the `Copyright` line? I couldn't find an example in this project. Based on the footer of text at https://www.contributor-covenant.org ("The Contributor Covenant was created by Coraline Ada Ehmke in 2014 and is released under the CC BY 4.0 License.") I was thinking:

````
Copyright 2014-2017 Coraline Ada Ehmke and contributors
````

Which would lead to:

````
Contributor Covenant
https://www.contributor-covenant.org
Copyright 2014-2017 Coraline Ada Ehmke and contributors
This Code of Conduct is adapted from the Contributor Covenant, version 1.4, available at https://www.contributor-covenant.org/version/1/4/code-of-conduct.html
````

If this works, can it be added somewhere in this project?

**Notes:**

* The optional URL is required in the case of CC-BY. In this case it appears to be https://www.contributor-covenant.org (not the version specific link or http://where.coraline.codes which is used in the footer)
* Please let me know if I've got any details wrong, or missed an existing human- or machine-readable source for this information.

**Comment by nogweii** [comment]
Since this was opened, the org was created. @CoralineAda would it be correct to assume the org owns the copyright now? So a SPDX attribution of a copy of the contributor covenant in a repo could be something like:

```
SPDX-License: CC-BY-4.0
SPDX-FileCopyrightText: Organization for Ethical Source
```

**Comment by CoralineAda** [comment]
@nogweii that's correct, OES owns the copyright now.
